<a href="https://colab.research.google.com/github/SeneshaMandakini/SriLankan_Tourism_Dashboard/blob/main/Tourism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lag setup

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

# Upload the first zip file
upload = files.upload()

Saving TA.xlsx to TA (1).xlsx


In [ ]:
df = pd.read_excel('TA.xlsx')

In [ ]:
df

Year Month  Tourist arrivals
0    2014   Jan            146575
1    2014   Feb            141878
2    2014   Mar            133048
3    2014   Apr            112631
4    2014   May             90046
..    ...   ...               ...
115  2023   Aug            136405
116  2023   Sep            111938
117  2023   Oct            109199
118  2023   Nov            151496
119  2023   Dec            210352

[120 rows x 3 columns]

In [ ]:
df['lag_1'] = df['Tourist arrivals'].shift(1)
df['lag_2'] = df['Tourist arrivals'].shift(2)
df['lag_3'] = df['Tourist arrivals'].shift(3)

In [ ]:
print(df.head(10))

   Year Month  Tourist arrivals     lag_1     lag_2     lag_3
0  2014   Jan            146575       NaN       NaN       NaN
1  2014   Feb            141878  146575.0       NaN       NaN
2  2014   Mar            133048  141878.0  146575.0       NaN
3  2014   Apr            112631  133048.0  141878.0  146575.0
4  2014   May             90046  112631.0  133048.0  141878.0
5  2014   Jun            103175   90046.0  112631.0  133048.0
6  2014   Jul            133971  103175.0   90046.0  112631.0
7  2014   Aug            140319  133971.0  103175.0   90046.0
8  2014   Sep            105535  140319.0  133971.0  103175.0
9  2014   Oct            121576  105535.0  140319.0  133971.0


In [ ]:
df.to_csv('TA with lag.csv', index=False)

In [ ]:
files.download('TA with lag.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#Sementic

In [ ]:
# Upload the first zip file
upload = files.upload()

Saving cleaned_reviews_with_sentiment_withreviews.xlsx to cleaned_reviews_with_sentiment_withreviews.xlsx


In [ ]:
df_1 = pd.read_excel('cleaned_reviews_with_sentiment_withreviews.xlsx')

In [ ]:
month_to_num = {
    'Jan': 1,
    'Feb': 2,
    'Mar': 3,
    'Apr': 4,
    'May': 5,
    'Jun': 6,
    'Jul': 7,
    'Aug': 8,
    'Sep': 9,
    'Oct': 10,
    'Nov': 11,
    'Dec': 12
}

In [ ]:
# Add a new column for month numbers using map
df_1['Month_Number'] = df_1['Month'].map(month_to_num)

In [ ]:
print(df_1.head(10))

  Month    Year                                             Review  \
0   Dec  2023.0  Early morning mid week visit gave us a quiet t...   
1   Mar  2023.0  This is one of the most spectacular warerfalls...   
2   Jan  2023.0  one of the best waterfall in Sri lanka .easy a...   
3   Jul  2022.0  it is a really nice walk through small pathway...   
4   Mar  2021.0  One of the beautiful waterfall in the universe...   
5   Jul  2020.0  Nice location... 45mins walk.. but totally wor...   
6   Jan  2020.0  Dunhinda water fall situated around 5KM away f...   
7   Apr  2019.0  It's not a walk in the park but there are a lo...   
8   Mar  2020.0  We went up with a guide called sudu.\nIf you g...   
9   Feb  2020.0  If you are in Badulla or Ella area don't miss ...   

   Sentiment Score Sentiment  Month_Number  
0         0.375000  Positive          12.0  
1         0.450000  Positive           3.0  
2         0.920000  Positive           1.0  
3         0.283333  Positive           7.0  
4   

In [ ]:
average_sentiment = df_1.groupby(['Month', 'Year'])['Sentiment Score'].mean().reset_index()

In [ ]:
# Display the result
print(average_sentiment)

    Month    Year  Sentiment Score
0     Apr  2011.0         0.204594
1     Apr  2012.0         0.273176
2     Apr  2013.0         0.264847
3     Apr  2014.0         0.271197
4     Apr  2015.0         0.282783
..    ...     ...              ...
156   Sep  2019.0         0.333647
157   Sep  2020.0         0.411378
158   Sep  2021.0         0.417800
159   Sep  2022.0         0.333101
160   Sep  2023.0         0.376511

[161 rows x 3 columns]


In [ ]:
# Add a new column for month numbers using map
average_sentiment['Month_Number'] = average_sentiment['Month'].map(month_to_num).astype(int)

In [ ]:
# Drop the 'Month' column and rename 'Month_Number' to 'Month'
average_sentiment.drop(columns=['Month'], inplace=True)
average_sentiment.rename(columns={'Month_Number': 'Month'}, inplace=True)

In [ ]:
average_sentiment

Year  Sentiment Score  Month
0    2011.0         0.204594      4
1    2012.0         0.273176      4
2    2013.0         0.264847      4
3    2014.0         0.271197      4
4    2015.0         0.282783      4
..      ...              ...    ...
156  2019.0         0.333647      9
157  2020.0         0.411378      9
158  2021.0         0.417800      9
159  2022.0         0.333101      9
160  2023.0         0.376511      9

[161 rows x 3 columns]

In [ ]:
average_sentiment.to_csv('average_sentiment_scores.csv', index=False)

In [ ]:
files.download('average_sentiment_scores.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#Combine the tables

In [ ]:
upload = files.upload()

Saving Final Climate data.xlsx to Final Climate data.xlsx


In [ ]:
df_2 = pd.read_excel('Final Climate data.xlsx')

In [ ]:
df_2

Year  Month  Wind Speed_x  Wind Speed_y  RH Max Average  RH Min Average  \
0    2014      1           7.6           5.4       82.774194       68.870968   
1    2014      2           6.9           3.5       84.678571       66.785714   
2    2014      3           6.5           3.3       86.096774       68.741935   
3    2014      4           4.8           2.6       89.533333       75.066667   
4    2014      5           7.1           4.5       87.225806       76.967742   
..    ...    ...           ...           ...             ...             ...   
115  2023      8           NaN           NaN             NaN             NaN   
116  2023      9           NaN           NaN             NaN             NaN   
117  2023     10           NaN           NaN             NaN             NaN   
118  2023     11           NaN           NaN             NaN             NaN   
119  2023     12           NaN           NaN             NaN             NaN   

     Temp Max Average  Temp Min Average  
0           31.370968         23.648387  
1           31.639286         23.607143  
2           32.348387         24.809677  
3           32.230000         25.263333  
4           31.606452         26.580645  
..                ...               ...  
115               NaN               NaN  
116               NaN               NaN  
117               NaN               NaN  
118               NaN               NaN  
119               NaN               NaN  

[120 rows x 8 columns]

In [ ]:
# Concatenate or merge DataFrames based on 'Month' and 'Year'
combined_df = pd.concat([df, average_sentiment, df_2], ignore_index=True)

In [ ]:
# Display the combined DataFrame
print(combined_df)

       Year Month  Tourist arrivals     lag_1     lag_2     lag_3  \
0    2014.0   Jan          146575.0       NaN       NaN       NaN   
1    2014.0   Feb          141878.0  146575.0       NaN       NaN   
2    2014.0   Mar          133048.0  141878.0  146575.0       NaN   
3    2014.0   Apr          112631.0  133048.0  141878.0  146575.0   
4    2014.0   May           90046.0  112631.0  133048.0  141878.0   
..      ...   ...               ...       ...       ...       ...   
396  2023.0     8               NaN       NaN       NaN       NaN   
397  2023.0     9               NaN       NaN       NaN       NaN   
398  2023.0    10               NaN       NaN       NaN       NaN   
399  2023.0    11               NaN       NaN       NaN       NaN   
400  2023.0    12               NaN       NaN       NaN       NaN   

     Sentiment Score  Wind Speed_x  Wind Speed_y  RH Max Average  \
0                NaN           NaN           NaN             NaN   
1                NaN           NaN 

In [ ]:
combined_df.to_csv('combined_df.csv', index=False)

In [ ]:
files.download('combined_df.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#Load and Split data

In [ ]:
import pandas as pd

In [ ]:
#Import numpy for performing the statistical and mathematical operations on the data set
import numpy as np

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error

In [ ]:
from sklearn.model_selection import TimeSeriesSplit

In [ ]:
from sklearn import preprocessing

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
from google.colab import files
upload = files.upload()

Saving combined_df.xlsx to combined_df.xlsx


In [ ]:
#To read text files
from numpy import loadtxt

In [ ]:
TA = pd.read_excel('combined_df.xlsx')

In [ ]:
TA

Year  Month  Tourist arrivals     lag_1     lag_2     lag_3  \
0    2014      1          146575.0       NaN       NaN       NaN   
1    2014      2          141878.0  146575.0       NaN       NaN   
2    2014      3          133048.0  141878.0  146575.0       NaN   
3    2014      4          112631.0  133048.0  141878.0  146575.0   
4    2014      5           90046.0  112631.0  133048.0  141878.0   
..    ...    ...               ...       ...       ...       ...   
115  2023      8          136405.0  143039.0  100388.0   83309.0   
116  2023      9          111938.0  136405.0  143039.0  100388.0   
117  2023     10          109199.0  111938.0  136405.0  143039.0   
118  2023     11          151496.0  109199.0  111938.0  136405.0   
119  2023     12          210352.0  151496.0  109199.0  111938.0   

     Sentiment Score  Wind Speed_x  Wind Speed_y  RH Max Average  \
0           0.253131           7.6           5.4       82.774194   
1           0.264427           6.9           3.5       84.678571   
2           0.268167           6.5           3.3       86.096774   
3           0.271197           4.8           2.6       89.533333   
4           0.273640           7.1           4.5       87.225806   
..               ...           ...           ...             ...   
115         0.380155           NaN           NaN             NaN   
116         0.376511           NaN           NaN             NaN   
117         0.349064           NaN           NaN             NaN   
118         0.387670           NaN           NaN             NaN   
119         0.355502           NaN           NaN             NaN   

     RH Min Average  Temp Max Average  Temp Min Average  
0         68.870968         31.370968         23.648387  
1         66.785714         31.639286         23.607143  
2         68.741935         32.348387         24.809677  
3         75.066667         32.230000         25.263333  
4         76.967742         31.606452         26.580645  
..              ...               ...               ...  
115             NaN               NaN               NaN  
116             NaN               NaN               NaN  
117             NaN               NaN               NaN  
118             NaN               NaN               NaN  
119             NaN               NaN               NaN  

[120 rows x 13 columns]

In [ ]:
np.random.seed(0)


In [ ]:
# Drop rows with NaN values
TA = TA.dropna()

In [ ]:
TA

Year  Month  Tourist arrivals     lag_1     lag_2     lag_3  \
3    2014      4          112631.0  133048.0  141878.0  146575.0   
4    2014      5           90046.0  112631.0  133048.0  141878.0   
5    2014      6          103175.0   90046.0  112631.0  133048.0   
6    2014      7          133971.0  103175.0   90046.0  112631.0   
7    2014      8          140319.0  133971.0  103175.0   90046.0   
..    ...    ...               ...       ...       ...       ...   
110  2023      3          125495.0  107639.0  102545.0   91961.0   
111  2023      4          105498.0  125495.0  107639.0  102545.0   
112  2023      5           83309.0  105498.0  125495.0  107639.0   
113  2023      6          100388.0   83309.0  105498.0  125495.0   
114  2023      7          143039.0  100388.0   83309.0  105498.0   

     Sentiment Score  Wind Speed_x  Wind Speed_y  RH Max Average  \
3           0.271197      4.800000      2.600000       89.533333   
4           0.273640      7.100000      4.500000       87.225806   
5           0.296411      7.400000      7.100000       85.733333   
6           0.285558      8.700000      6.100000       84.645161   
7           0.289428      6.400000      4.900000       87.580645   
..               ...           ...           ...             ...   
110         0.385755      5.755556      3.155556       87.709677   
111         0.388341      5.233333      2.777778       88.733333   
112         0.373074      6.211111      4.355556       87.548387   
113         0.298359      6.222222      5.377778       85.433333   
114         0.395037      6.566667      5.166667       85.451613   

     RH Min Average  Temp Max Average  Temp Min Average  
3         75.066667         32.230000         25.263333  
4         76.967742         31.606452         26.580645  
5         78.533333         30.980000         27.096667  
6         76.322581         30.883871         26.796774  
7         78.870968         30.183871         25.554839  
..              ...               ...               ...  
110       73.225806         31.977419         24.577419  
111       72.900000         32.330000         25.310000  
112       77.935484         31.677419         26.293548  
113       78.700000         31.276667         26.750000  
114       78.096774         30.670968         26.729032  

[109 rows x 13 columns]

In [ ]:
TA['Tourist arrivals'] = np.log(TA['Tourist arrivals'])

In [ ]:
tscv = TimeSeriesSplit(n_splits=5)

In [ ]:
train_percentage = 0.8

In [ ]:
split_index = int(len(TA) * train_percentage)

In [ ]:
train_data = TA.iloc[:split_index]
test_data = TA.iloc[split_index:]

In [ ]:
test_data.head()

Year  Month  Tourist arrivals    lag_1    lag_2    lag_3  Sentiment Score  \
92  2021      9          9.513920   5040.0   2429.0   1614.0         0.417800   
93  2021     10         10.033243  13547.0   5040.0   2429.0         0.423893   
94  2021     11         10.698605  22771.0  13547.0   5040.0         0.373637   
95  2021     12         11.402061  44294.0  22771.0  13547.0         0.362490   
96  2022      1         11.318454  89506.0  44294.0  22771.0         0.348738   

    Wind Speed_x  Wind Speed_y  RH Max Average  RH Min Average  \
92           5.1           4.7       87.166667       78.900000   
93           3.3           3.5       90.032258       79.580645   
94           3.4           3.3       91.200000       80.966667   
95           6.0           4.2       86.774194       70.741935   
96           5.1           3.1       83.806452       67.387097   

    Temp Max Average  Temp Min Average  
92         30.440000         25.866667  
93         30.370968         25.229032  
94         29.836667         24.316667  
95         31.606452         24.061290  
96         32.177419         23.938710

In [ ]:
Train_year = train_data[['Year','Month']]
Test_year = test_data[['Year','Month']]

In [ ]:
Test_year

Year  Month
92   2021      9
93   2021     10
94   2021     11
95   2021     12
96   2022      1
97   2022      2
98   2022      3
99   2022      4
100  2022      5
101  2022      6
102  2022      7
103  2022      8
104  2022      9
105  2022     10
106  2022     11
107  2022     12
108  2023      1
110  2023      3
111  2023      4
112  2023      5
113  2023      6
114  2023      7

#Past Tourism Arrivals

In [ ]:
X_train_1, y_train_1= train_data[['lag_1','lag_2', 'lag_3']], train_data['Tourist arrivals']
X_test_1, y_test_1 = test_data[['lag_1','lag_2', 'lag_3']], test_data['Tourist arrivals']

In [ ]:
# Initialize MinMaxScaler
scaler = MinMaxScaler()

In [ ]:
# Fit the scaler on the training data and transform it
X_train_scaled_1 = scaler.fit_transform(X_train_1)

# Transform the testing data
X_test_scaled_1 = scaler.transform(X_test_1)

In [ ]:
rf_model_past = RandomForestRegressor(random_state=42)
rf_model_past.fit(X_train_scaled_1, y_train_1)

RandomForestRegressor(random_state=42)

In [ ]:
# rf_model is your trained random forest model
params_past = rf_model_past.get_params()

In [ ]:
# Print the parameters
print("Parameters used in the Random Forest model:")
print(params_past)

Parameters used in the Random Forest model:
{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


In [ ]:
rf_model_past.score(X_train_scaled_1, y_train_1)

0.9526255457422304

In [ ]:
y_pred_1 = rf_model_past.predict(X_test_scaled_1)

In [ ]:
np.random.seed(0)

In [ ]:
y_pred_1

array([ 8.31728562,  7.85144116,  8.75680886, 10.60455126, 11.53798937,
       11.6894789 , 11.72680549, 11.76815815, 11.71473624, 11.03729044,
       10.55104675, 10.89051385, 11.38957702, 10.86839814, 11.01483988,
       11.5270375 , 11.69980486, 11.76924053, 11.86634841, 11.7831878 ,
       11.6492924 , 11.76991959])

In [ ]:
#Mean Squared Error (MSE)
mse_1= mean_squared_error(y_test_1, y_pred_1)
print(f'Mean Squared Error (MSE): {mse_1}')

Mean Squared Error (MSE): 0.697866657264547


In [ ]:
y_test_antilog = np.exp(y_test_1)
y_pred_antilog = np.exp(y_pred_1)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_1 = pd.DataFrame(X_test_scaled_1, columns=[f'feature_{i}' for i in range(X_test_scaled_1.shape[1])])
test_results_1['Actual'] = y_test_antilog
test_results_1['Predicted'] = y_pred_antilog

In [ ]:
y_test_antilog

92      13547.0
93      22771.0
94      44294.0
95      89506.0
96      82327.0
97      96507.0
98     106500.0
99      62980.0
100     30207.0
101     32856.0
102     47293.0
103     37760.0
104     29802.0
105     42026.0
106     59759.0
107     91961.0
108    102545.0
110    125495.0
111    105498.0
112     83309.0
113    100388.0
114    143039.0
Name: Tourist arrivals, dtype: float64

In [ ]:
y_pred_antilog

array([  4094.03215335,   2569.43461642,   6353.80331021,  40317.9179719 ,
       102538.06406773, 119309.8178575 , 123847.40643668, 129076.1931548 ,
       122361.64449243,  62149.02687444,  38217.42133079,  53664.8686804 ,
        88395.55996473,  52491.0596726 ,  60769.29229424, 101421.20842366,
       120548.18917904, 129215.97840346, 142393.32601327, 131030.8146104 ,
       114610.23662173, 129303.75269393])

In [ ]:
y_pred_antilog

array([  4094.03215335,   2569.43461642,   6353.80331021,  40317.9179719 ,
       102538.06406773, 119309.8178575 , 123847.40643668, 129076.1931548 ,
       122361.64449243,  62149.02687444,  38217.42133079,  53664.8686804 ,
        88395.55996473,  52491.0596726 ,  60769.29229424, 101421.20842366,
       120548.18917904, 129215.97840346, 142393.32601327, 131030.8146104 ,
       114610.23662173, 129303.75269393])

In [ ]:
y_pred_1

array([ 8.31728562,  7.85144116,  8.75680886, 10.60455126, 11.53798937,
       11.6894789 , 11.72680549, 11.76815815, 11.71473624, 11.03729044,
       10.55104675, 10.89051385, 11.38957702, 10.86839814, 11.01483988,
       11.5270375 , 11.69980486, 11.76924053, 11.86634841, 11.7831878 ,
       11.6492924 , 11.76991959])

In [ ]:
test_results_1

feature_0  feature_1  feature_2  Actual      Predicted
0    0.014078   0.008055   0.004830     NaN    4094.032153
1    0.047880   0.018384   0.008055     NaN    2569.434616
2    0.084531   0.052038   0.018384     NaN    6353.803310
3    0.170051   0.088529   0.052038     NaN   40317.917972
4    0.349697   0.173676   0.088529     NaN  102538.064068
5    0.321172   0.352537   0.173676     NaN  119309.817857
6    0.377515   0.324137   0.352537     NaN  123847.406437
7    0.417222   0.380234   0.324137     NaN  129076.193155
8    0.244298   0.419767   0.380234     NaN  122361.644492
9    0.114077   0.247599   0.419767     NaN   62149.026874
10   0.124603   0.117946   0.247599     NaN   38217.421331
11   0.181967   0.128426   0.117946     NaN   53664.868680
12   0.144088   0.185540   0.128426     NaN   88395.559965
13   0.112468   0.147827   0.185540     NaN   52491.059673
14   0.161039   0.116344   0.147827     NaN   60769.292294
15   0.231500   0.164703   0.116344     NaN  101421.208424
16   0.359452   0.234856   0.164703     NaN  120548.189179
17   0.421747   0.404121   0.362250     NaN  129215.978403
18   0.492697   0.424273   0.404121     NaN  142393.326013
19   0.413240   0.494912   0.424273     NaN  131030.814610
20   0.325074   0.415803   0.494912     NaN  114610.236622
21   0.392936   0.328022   0.415803     NaN  129303.752694

In [ ]:
test_results_1.to_csv('Tourism_Past.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_Past.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

##RF after tuning parameters

In [ ]:
# Set random seed for NumPy
np.random.seed(0)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# Define hyperparameters to search
param_grid_rf_1 = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2, 3, 4],
    'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
    'bootstrap': [True, False]
}

In [ ]:
# Perform Grid Search with 5-fold cross-validation
grid_search_rf_1 = GridSearchCV(estimator=rf_model_past, param_grid=param_grid_rf_1, cv=tscv, scoring='neg_mean_squared_error')
grid_search_rf_1.fit(X_train_scaled_1, y_train_1)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=RandomForestRegressor(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'max_depth': [3, 5, 7, 10, None],
                         'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 4, 6, 8, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='neg_mean_squared_error')

In [ ]:
# Get the best parameters
best_params_rf_1 = grid_search_rf_1.best_params_

In [ ]:
# Train the model with the best parameters
best_rf_model_1 = RandomForestRegressor(**best_params_rf_1, random_state=42)
best_rf_model_1.fit(X_train_scaled_1, y_train_1)

RandomForestRegressor(bootstrap=False, max_depth=7, max_features=None,
                      min_samples_leaf=3, random_state=42)

In [ ]:
best_rf_model_1.score(X_train_scaled_1, y_train_1)

0.8342149413484583

In [ ]:
# Make predictions and evaluate the model
y_pred_best_rf_1 = best_rf_model_1.predict(X_test_scaled_1)
mse_best_rf_1 = mean_squared_error(y_test_1, y_pred_best_rf_1)


In [ ]:
print(f'Best Parameters: {best_params_rf_1}')
print(f'Mean Squared Error (MSE) with Best Model: {mse_best_rf_1}')

Best Parameters: {'bootstrap': False, 'max_depth': 7, 'max_features': None, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 100}
Mean Squared Error (MSE) with Best Model: 0.6861239577511152


In [ ]:
y_test_antilog = np.exp(y_test_1)
y_pred_antilog = np.exp(y_pred_best_rf_1)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_1 = pd.DataFrame(X_test_scaled_1, columns=[f'feature_{i}' for i in range(X_test_scaled_1.shape[1])])
test_results_1['Actual'] = y_test_antilog
test_results_1['Predicted'] = y_pred_antilog

In [ ]:
y_test_antilog

92      13547.0
93      22771.0
94      44294.0
95      89506.0
96      82327.0
97      96507.0
98     106500.0
99      62980.0
100     30207.0
101     32856.0
102     47293.0
103     37760.0
104     29802.0
105     42026.0
106     59759.0
107     91961.0
108    102545.0
110    125495.0
111    105498.0
112     83309.0
113    100388.0
114    143039.0
Name: Tourist arrivals, dtype: float64

In [ ]:
y_pred_antilog

array([  4582.53910301,   4582.53910301,  16480.65424157, 118853.03768059,
       118853.03768059, 118853.03768059, 118853.03768059, 118853.03768059,
       118853.03768059, 118853.03768059, 118853.03768059, 118853.03768059,
       118853.03768059, 118853.03768059, 118853.03768059, 118853.03768059,
       118853.03768059, 118853.03768059, 175294.72729752, 118853.03768059,
       118853.03768059, 118853.03768059])

In [ ]:
y_pred_1

array([ 8.31728562,  7.85144116,  8.75680886, 10.60455126, 11.53798937,
       11.6894789 , 11.72680549, 11.76815815, 11.71473624, 11.03729044,
       10.55104675, 10.89051385, 11.38957702, 10.86839814, 11.01483988,
       11.5270375 , 11.69980486, 11.76924053, 11.86634841, 11.7831878 ,
       11.6492924 , 11.76991959])

In [ ]:
test_results_1

feature_0  feature_1  feature_2  Actual      Predicted
0    0.014078   0.008055   0.004830     NaN    4582.539103
1    0.047880   0.018384   0.008055     NaN    4582.539103
2    0.084531   0.052038   0.018384     NaN   16480.654242
3    0.170051   0.088529   0.052038     NaN  118853.037681
4    0.349697   0.173676   0.088529     NaN  118853.037681
5    0.321172   0.352537   0.173676     NaN  118853.037681
6    0.377515   0.324137   0.352537     NaN  118853.037681
7    0.417222   0.380234   0.324137     NaN  118853.037681
8    0.244298   0.419767   0.380234     NaN  118853.037681
9    0.114077   0.247599   0.419767     NaN  118853.037681
10   0.124603   0.117946   0.247599     NaN  118853.037681
11   0.181967   0.128426   0.117946     NaN  118853.037681
12   0.144088   0.185540   0.128426     NaN  118853.037681
13   0.112468   0.147827   0.185540     NaN  118853.037681
14   0.161039   0.116344   0.147827     NaN  118853.037681
15   0.231500   0.164703   0.116344     NaN  118853.037681
16   0.359452   0.234856   0.164703     NaN  118853.037681
17   0.421747   0.404121   0.362250     NaN  118853.037681
18   0.492697   0.424273   0.404121     NaN  175294.727298
19   0.413240   0.494912   0.424273     NaN  118853.037681
20   0.325074   0.415803   0.494912     NaN  118853.037681
21   0.392936   0.328022   0.415803     NaN  118853.037681

In [ ]:
test_results_1.to_csv('Tourism_Past.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_Past.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#Sentiment With Tourists arrivals

In [ ]:
X_train_2, y_train_2= train_data[['Sentiment Score']], train_data['Tourist arrivals']
X_test_2, y_test_2 = test_data[['Sentiment Score']], test_data['Tourist arrivals']

In [ ]:
# Fit the scaler on the training data and transform it
X_train_scaled_2 = scaler.fit_transform(X_train_2)

# Transform the testing data
X_test_scaled_2 = scaler.transform(X_test_2)

In [ ]:
X_train_2

Sentiment Score
3          0.271197
4          0.273640
5          0.296411
6          0.285558
7          0.289428
..              ...
87         0.391649
88         0.325016
89         0.402484
90         0.466978
91         0.443652

[87 rows x 1 columns]

In [ ]:
rf_model_sentiment = RandomForestRegressor(random_state=42)
rf_model_sentiment.fit(X_train_scaled_2, y_train_2)

RandomForestRegressor(random_state=42)

In [ ]:
# rf_model is your trained random forest model
params_sentiment = rf_model_sentiment.get_params()

In [ ]:
# Print the parameters
print("Parameters used in the Random Forest model:")
print(params_sentiment)

Parameters used in the Random Forest model:
{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


In [ ]:
np.random.seed(0)

In [ ]:
rf_model_sentiment.score(X_train_scaled_2, y_train_2)

0.8736137415998795

In [ ]:
y_pred_2 = rf_model_sentiment.predict(X_test_scaled_2)

In [ ]:
y_pred_2

array([10.62839126, 10.6981011 , 11.73493599, 11.69598562, 11.68646499,
       11.55711835, 11.68646499, 11.19705123,  8.51284444, 10.6981011 ,
       11.18684389, 11.18105707, 11.70843419, 11.59818547,  9.27798107,
       11.73493599,  9.5718399 , 11.19705123,  9.5718399 , 11.73493599,
       12.22572489, 11.61612619])

In [ ]:
#Mean Squared Error (MSE)
mse_2= mean_squared_error(y_test_2, y_pred_2)
print(f'Mean Squared Error (MSE): {mse_2}')

Mean Squared Error (MSE): 1.0055794582137916


##RF after tuning parameters

In [ ]:
# Set random seed for NumPy
np.random.seed(0)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# Define hyperparameters to search
param_grid_rf_2 = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2, 3, 4],
    'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
    'bootstrap': [True, False]
}

In [ ]:
# Perform Grid Search with 5-fold cross-validation
grid_search_rf_2 = GridSearchCV(estimator=rf_model_sentiment, param_grid=param_grid_rf_2, cv=tscv, scoring='neg_mean_squared_error')
grid_search_rf_2.fit(X_train_scaled_2, y_train_2)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=RandomForestRegressor(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'max_depth': [3, 5, 7, 10, None],
                         'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 4, 6, 8, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='neg_mean_squared_error')

In [ ]:
# Get the best parameters
best_params_rf_2 = grid_search_rf_2.best_params_

In [ ]:
# Train the model with the best parameters
best_rf_model_2 = RandomForestRegressor(**best_params_rf_2, random_state=42)
best_rf_model_2.fit(X_train_scaled_2, y_train_2)

RandomForestRegressor(max_depth=10, max_features='sqrt', min_samples_leaf=4,
                      min_samples_split=10, n_estimators=50, random_state=42)

In [ ]:
best_rf_model_2.score(X_train_scaled_2, y_train_2)

0.37141756759578626

In [ ]:
X_test_scaled_2

array([[0.77101284],
       [0.79938543],
       [0.56537471],
       [0.51347291],
       [0.44944026],
       [0.5723449 ],
       [0.43940243],
       [0.61110773],
       [0.89759411],
       [0.80631424],
       [0.57986967],
       [0.57501527],
       [0.37662714],
       [0.51429744],
       [0.70523338],
       [0.56898707],
       [0.63570602],
       [0.62179923],
       [0.63384431],
       [0.56275289],
       [0.21485757],
       [0.66502063]])

In [ ]:
# Make predictions and evaluate the model
y_pred_best_rf_2 = best_rf_model_2.predict(X_test_scaled_2)
mse_best_rf_2 = mean_squared_error(y_test_2, y_pred_best_rf_2)


In [ ]:
print(f'Best Parameters: {best_params_rf_2}')
print(f'Mean Squared Error (MSE) with Best Model: {mse_best_rf_2}')

Best Parameters: {'bootstrap': True, 'max_depth': 10, 'max_features': 'sqrt', 'min_samples_leaf': 4, 'min_samples_split': 10, 'n_estimators': 50}
Mean Squared Error (MSE) with Best Model: 0.39237404293284295


In [ ]:
y_test_antilog_2 = np.exp(y_test_2)
y_pred_antilog_2 = np.exp(y_pred_best_rf_2)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_2 = pd.DataFrame(X_test_scaled_2, columns=[f'feature_{i}' for i in range(X_test_scaled_2.shape[1])])
test_results_2['Actual'] = y_test_antilog_2
test_results_2['Predicted'] = y_pred_antilog_2

In [ ]:
test_results_2

feature_0  Actual      Predicted
0    0.771013     NaN   22656.970954
1    0.799385     NaN   22656.970954
2    0.565375     NaN   80662.653124
3    0.513473     NaN   82701.910427
4    0.449440     NaN   87083.030131
5    0.572345     NaN   73552.892803
6    0.439402     NaN   87083.030131
7    0.611108     NaN   60338.886932
8    0.897594     NaN   22656.970954
9    0.806314     NaN   22656.970954
10   0.579870     NaN   62686.862256
11   0.575015     NaN   62686.862256
12   0.376627     NaN   83075.599137
13   0.514297     NaN   82701.910427
14   0.705233     NaN   22656.970954
15   0.568987     NaN   80662.653124
16   0.635706     NaN   38883.137998
17   0.621799     NaN   60338.886932
18   0.633844     NaN   38883.137998
19   0.562753     NaN   80662.653124
20   0.214858     NaN  161054.142908
21   0.665021     NaN   32884.924871

In [ ]:
test_results_2.to_csv('Tourism_Sentiment.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_Sentiment.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#Climate Variables with Tourists arrivals

In [ ]:
X_train_3, y_train_3= train_data[['Wind Speed_x', 'Wind Speed_y', 'RH Max Average', 'RH Min Average', 'Temp Max Average', 'Temp Min Average']], train_data['Tourist arrivals']
X_test_3, y_test_3 = test_data[['Wind Speed_x', 'Wind Speed_y', 'RH Max Average', 'RH Min Average', 'Temp Max Average', 'Temp Min Average']], test_data['Tourist arrivals']

In [ ]:
# Fit the scaler on the training data and transform it
X_train_scaled_3 = scaler.fit_transform(X_train_3)

# Transform the testing data
X_test_scaled_3 = scaler.transform(X_test_3)

In [ ]:
rf_model_Climate = RandomForestRegressor(random_state=42)
rf_model_Climate.fit(X_train_scaled_3, y_train_3)

RandomForestRegressor(random_state=42)

In [ ]:
np.random.seed(0)

In [ ]:
# rf_model is your trained random forest model
params_Climate = rf_model_Climate.get_params()

In [ ]:
# Print the parameters
print("Parameters used in the Random Forest model:")
print(params_Climate)

Parameters used in the Random Forest model:
{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


In [ ]:
rf_model_Climate.score(X_train_scaled_3, y_train_3)

0.8508035458102291

In [ ]:
y_pred_3 = rf_model_Climate.predict(X_test_scaled_3)

In [ ]:
y_pred_3

array([11.49140689, 11.64054393, 11.21744959, 12.24447601, 12.04691466,
       11.45450418, 11.86961466, 11.62362437, 10.47290825, 10.48261329,
       10.42650757, 10.53113626, 11.49658312, 10.98977015, 11.10287537,
       11.33962319, 12.17957675, 11.92567101, 11.76500988, 11.32359523,
       11.07260877, 11.13190681])

In [ ]:
#Mean Squared Error (MSE)
mse_3= mean_squared_error(y_test_3, y_pred_3)
print(f'Mean Squared Error (MSE): {mse_3}')

Mean Squared Error (MSE): 0.6157077393299365


In [ ]:
y_test_antilog_3 = np.exp(y_test_3)
y_pred_antilog_3 = np.exp(y_pred_3)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_3 = pd.DataFrame(X_test_scaled_3, columns=[f'feature_{i}' for i in range(X_test_scaled_3.shape[1])])
test_results_3['Actual'] = y_test_antilog_3
test_results_3['Predicted'] = y_pred_antilog_3

In [ ]:
test_results_3

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  Actual  \
0    0.409836   0.492308   0.555419   0.859197   0.233079   0.696810     NaN   
1    0.114754   0.307692   0.759802   0.896057   0.214700   0.547852     NaN   
2    0.131148   0.276923   0.843089   0.971117   0.072454   0.334715     NaN   
3    0.557377   0.415385   0.527426   0.417397   0.543621   0.275057     NaN   
4    0.409836   0.246154   0.315758   0.235716   0.695629   0.246420     NaN   
5    0.688525   0.415385   0.097762   0.172202   0.672165   0.294111     NaN   
6    0.606557   0.446154   0.230630   0.375471   0.760039   0.694047     NaN   
7    0.360656   0.169231   0.728972   0.711173   0.586275   0.572218     NaN   
8    0.540984   0.523077   0.483712   0.910033   0.377014   0.818387     NaN   
9    0.491803   0.400000   0.476963   0.922378   0.293424   0.873574     NaN   
10   0.377049   0.384615   0.396284   0.766784   0.250770   0.804069     NaN   
11   0.442623   0.476923   0.407788   0.758049   0.119373   0.756594     NaN   
12   0.557377   0.400000   0.400885   0.718394   0.189595   0.744310     NaN   
13   0.409836   0.476923   0.644765   0.924008   0.092751   0.522231     NaN   
14   0.524590   0.153846   0.693310   0.620915   0.288987   0.326149     NaN   
15   0.672131   0.553846   0.647065   0.550164   0.221571   0.186134     NaN   
16   0.681239   0.519658   0.267442   0.300352   0.394190   0.070836     NaN   
17   0.517304   0.254701   0.594148   0.551911   0.642383   0.395629     NaN   
18   0.431694   0.196581   0.667159   0.534267   0.736250   0.566767     NaN   
19   0.591985   0.439316   0.582644   0.806964   0.562515   0.796534     NaN   
20   0.593807   0.596581   0.431792   0.848366   0.455823   0.903165     NaN   
21   0.650273   0.564103   0.433096   0.815698   0.294569   0.898267     NaN   

        Predicted  
0   100380.311400  
1   127282.837832  
2    66624.518024  
3   221600.098399  
4   183240.918191  
5   149302.210835  
6   159494.596473  
7   126674.272847  
8    49502.441353  
9    49981.520475  
10   41875.392827  
11   46921.372134  
12   95780.705312  
13   64710.331338  
14   79955.343196  
15   54972.834375  
16  191298.847821  
17  136194.367099  
18  104097.963299  
19   91052.083198  
20   57677.669719  
21   52338.823427

In [ ]:
test_results_3.to_csv('Tourism_Climate.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_Climate.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

##RF after tuning parameters

In [ ]:
# Set random seed for NumPy
np.random.seed(0)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# Define hyperparameters to search
param_grid_rf_3 = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2, 3, 4],
    'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
    'bootstrap': [True, False]
}

In [ ]:
# Perform Grid Search with 5-fold cross-validation
grid_search_rf_3 = GridSearchCV(estimator=rf_model_Climate, param_grid=param_grid_rf_3, cv=tscv, scoring='neg_mean_squared_error')
grid_search_rf_3.fit(X_train_scaled_3, y_train_3)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=RandomForestRegressor(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'max_depth': [3, 5, 7, 10, None],
                         'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 4, 6, 8, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='neg_mean_squared_error')

In [ ]:
# Get the best parameters
best_params_rf_3 = grid_search_rf_3.best_params_

In [ ]:
# Train the model with the best parameters
best_rf_model_3 = RandomForestRegressor(**best_params_rf_3, random_state=42)
best_rf_model_3.fit(X_train_scaled_3, y_train_3)

RandomForestRegressor(bootstrap=False, max_depth=5, max_features=None,
                      min_samples_leaf=4, n_estimators=50, random_state=42)

In [ ]:
best_rf_model_3.score(X_train_scaled_3, y_train_3)

0.4244010220002079

In [ ]:
# Make predictions and evaluate the model
y_pred_best_rf_3 = best_rf_model_3.predict(X_test_scaled_3)
mse_best_rf_3 = mean_squared_error(y_test_3, y_pred_best_rf_3)


In [ ]:
print(f'Best Parameters: {best_rf_model_3}')
print(f'Mean Squared Error (MSE) with Best Model: {mse_best_rf_3}')


Best Parameters: RandomForestRegressor(bootstrap=False, max_depth=5, max_features=None,
                      min_samples_leaf=4, n_estimators=50, random_state=42)
Mean Squared Error (MSE) with Best Model: 1.1538542812810881


In [ ]:
y_test_antilog_3 = np.exp(y_test_3)
y_pred_antilog_3 = np.exp(y_pred_best_rf_3)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_3 = pd.DataFrame(X_test_scaled_3, columns=[f'feature_{i}' for i in range(X_test_scaled_3.shape[1])])
test_results_3['Actual'] = y_test_antilog_3
test_results_3['Predicted'] = y_pred_antilog_3

In [ ]:
test_results_3

In [ ]:
test_results_3.to_csv('Tourism_Climate.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_Climate.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

#With All variables

In [ ]:
X_train_4, y_train_4 = train_data[['Wind Speed_x', 'Wind Speed_y', 'RH Max Average', 'RH Min Average', 'Temp Max Average', 'Temp Min Average','Sentiment Score','lag_1','lag_2', 'lag_3']], train_data['Tourist arrivals']
X_test_4, y_test_4 = test_data[['Wind Speed_x', 'Wind Speed_y', 'RH Max Average', 'RH Min Average', 'Temp Max Average', 'Temp Min Average','Sentiment Score','lag_1','lag_2', 'lag_3']], test_data['Tourist arrivals']

In [ ]:
# Fit the scaler on the training data and transform it
X_train_scaled_4 = scaler.fit_transform(X_train_4)

# Transform the testing data
X_test_scaled_4 = scaler.transform(X_test_4)

In [ ]:
rf_model_all = RandomForestRegressor(random_state=42)
rf_model_all.fit(X_train_scaled_4, y_train_4)

RandomForestRegressor(random_state=42)

In [ ]:
# rf_model is your trained random forest model
params_all = rf_model_all.get_params()

In [ ]:
np.random.seed(0)

In [ ]:
# Print the parameters
print("Parameters used in the Random Forest model:")
print(params_all)

Parameters used in the Random Forest model:
{'bootstrap': True, 'ccp_alpha': 0.0, 'criterion': 'squared_error', 'max_depth': None, 'max_features': 1.0, 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


In [ ]:
rf_model_all.score(X_train_scaled_4, y_train_4)

0.943559647568152

In [ ]:
y_pred_4 = rf_model_all.predict(X_test_scaled_4)

In [ ]:
y_pred_4

array([ 8.20306453,  7.96580315,  8.99714274,  9.52088626, 10.38630057,
       10.25150725, 10.56776768, 11.72864583, 11.63954798, 10.94437786,
       10.5684758 , 11.04816245, 11.40732458, 10.87221795, 10.84853378,
       10.62536727, 10.09775965, 11.10884007, 11.12483954, 11.64325184,
       11.63148262, 11.73794261])

In [ ]:
#Mean Squared Error (MSE)
mse_4 = mean_squared_error(y_test_4, y_pred_4)
print(f'Mean Squared Error (MSE): {mse_4}')

Mean Squared Error (MSE): 1.5886607036855913


##RF after tuning parameters

In [ ]:
# Set random seed for NumPy
np.random.seed(0)

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# Define hyperparameters to search
param_grid_rf_4 = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 4, 6, 8, 10],
    'min_samples_leaf': [1, 2, 3, 4],
    'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
    'bootstrap': [True, False]
}

In [ ]:
# Perform Grid Search with 5-fold cross-validation
grid_search_rf_4 = GridSearchCV(estimator=rf_model_all, param_grid=param_grid_rf_4, cv=tscv, scoring='neg_mean_squared_error')
grid_search_rf_4.fit(X_train_scaled_4, y_train_4)

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=5, test_size=None),
             estimator=RandomForestRegressor(random_state=42),
             param_grid={'bootstrap': [True, False],
                         'max_depth': [3, 5, 7, 10, None],
                         'max_features': ['sqrt', 'log2', None, 2, 4, 6, 8, 10],
                         'min_samples_leaf': [1, 2, 3, 4],
                         'min_samples_split': [2, 4, 6, 8, 10],
                         'n_estimators': [50, 100, 150, 200]},
             scoring='neg_mean_squared_error')

In [ ]:
# Get the best parameters
best_params_rf_4 = grid_search_rf_4.best_params_

In [ ]:
# Train the model with the best parameters
best_rf_model_4 = RandomForestRegressor(**best_params_rf_4, random_state=42)
best_rf_model_4.fit(X_train_scaled_4, y_train_4)

RandomForestRegressor(bootstrap=False, max_depth=5, max_features=None,
                      min_samples_leaf=4, n_estimators=50, random_state=42)

In [ ]:
best_rf_model_4.score(X_train_scaled_4, y_train_4)

0.7801331801651925

In [ ]:
# Make predictions and evaluate the model
y_pred_best_rf_4 = best_rf_model_4.predict(X_test_scaled_4)
mse_best_rf_4 = mean_squared_error(y_test_4, y_pred_best_rf_4)


In [ ]:
print(f'Best Parameters: {best_params_rf_4}')
print(f'Mean Squared Error (MSE) with Best Model: {mse_best_rf_4}')


Best Parameters: {'bootstrap': False, 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 4, 'min_samples_split': 2, 'n_estimators': 50}
Mean Squared Error (MSE) with Best Model: 1.147353372907517


In [ ]:
y_test_antilog_4 = np.exp(y_test_4)
y_pred_antilog_4 = np.exp(y_pred_best_rf_4)

In [ ]:
# Create a DataFrame with the test data, actual values, and predicted values
test_results_4 = pd.DataFrame(X_test_scaled_4, columns=[f'feature_{i}' for i in range(X_test_scaled_4.shape[1])])
test_results_4['Actual'] = y_test_antilog_4
test_results_4['Predicted'] = y_pred_antilog_4

In [ ]:
test_results_4

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    0.409836   0.492308   0.555419   0.859197   0.233079   0.696810   
1    0.114754   0.307692   0.759802   0.896057   0.214700   0.547852   
2    0.131148   0.276923   0.843089   0.971117   0.072454   0.334715   
3    0.557377   0.415385   0.527426   0.417397   0.543621   0.275057   
4    0.409836   0.246154   0.315758   0.235716   0.695629   0.246420   
5    0.688525   0.415385   0.097762   0.172202   0.672165   0.294111   
6    0.606557   0.446154   0.230630   0.375471   0.760039   0.694047   
7    0.360656   0.169231   0.728972   0.711173   0.586275   0.572218   
8    0.540984   0.523077   0.483712   0.910033   0.377014   0.818387   
9    0.491803   0.400000   0.476963   0.922378   0.293424   0.873574   
10   0.377049   0.384615   0.396284   0.766784   0.250770   0.804069   
11   0.442623   0.476923   0.407788   0.758049   0.119373   0.756594   
12   0.557377   0.400000   0.400885   0.718394   0.189595   0.744310   
13   0.409836   0.476923   0.644765   0.924008   0.092751   0.522231   
14   0.524590   0.153846   0.693310   0.620915   0.288987   0.326149   
15   0.672131   0.553846   0.647065   0.550164   0.221571   0.186134   
16   0.681239   0.519658   0.267442   0.300352   0.394190   0.070836   
17   0.517304   0.254701   0.594148   0.551911   0.642383   0.395629   
18   0.431694   0.196581   0.667159   0.534267   0.736250   0.566767   
19   0.591985   0.439316   0.582644   0.806964   0.562515   0.796534   
20   0.593807   0.596581   0.431792   0.848366   0.455823   0.903165   
21   0.650273   0.564103   0.433096   0.815698   0.294569   0.898267   

    feature_6  feature_7  feature_8  feature_9  Actual      Predicted  
0    0.771013   0.014078   0.008055   0.004830     NaN    2940.535991  
1    0.799385   0.047880   0.018384   0.008055     NaN    2940.535991  
2    0.565375   0.084531   0.052038   0.018384     NaN   26300.729280  
3    0.513473   0.170051   0.088529   0.052038     NaN   33606.979031  
4    0.449440   0.349697   0.173676   0.088529     NaN   33606.979031  
5    0.572345   0.321172   0.352537   0.173676     NaN   33606.979031  
6    0.439402   0.377515   0.324137   0.352537     NaN   33606.979031  
7    0.611108   0.417222   0.380234   0.324137     NaN  113325.763082  
8    0.897594   0.244298   0.419767   0.380234     NaN  113325.763082  
9    0.806314   0.114077   0.247599   0.419767     NaN  113325.763082  
10   0.579870   0.124603   0.117946   0.247599     NaN  113325.763082  
11   0.575015   0.181967   0.128426   0.117946     NaN  113325.763082  
12   0.376627   0.144088   0.185540   0.128426     NaN  113325.763082  
13   0.514297   0.112468   0.147827   0.185540     NaN  113325.763082  
14   0.705233   0.161039   0.116344   0.147827     NaN  113325.763082  
15   0.568987   0.231500   0.164703   0.116344     NaN   33606.979031  
16   0.635706   0.359452   0.234856   0.164703     NaN   33606.979031  
17   0.621799   0.421747   0.404121   0.362250     NaN   33606.979031  
18   0.633844   0.492697   0.424273   0.404121     NaN   33606.979031  
19   0.562753   0.413240   0.494912   0.424273     NaN  113325.763082  
20   0.214858   0.325074   0.415803   0.494912     NaN  113325.763082  
21   0.665021   0.392936   0.328022   0.415803     NaN  113325.763082

In [ ]:
test_results_4.to_csv('Tourism_All.csv', index=False)

In [ ]:
# Download the CSV file
from google.colab import files
files.download('Tourism_All.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>